### ISSUE TITLE
Upgrading to the latest version of Symphony (v2.3.1)

### ISSUE THREAD

**Issue by drejohnson** [jdsimcoe/churchdeploy#2]
Do you have plans on updating to Symphony v2.3? I tried but I got a lot of errors due to incompatible extensions. I'm pretty new to Symphony but I like it's flexibility and this Ensemble is awesome.

**Comment by kirkstrobeck** [comment]
Currently all of the extensions that church deploy requires are not available in 2.3

**Comment by jdsimcoe** [comment]
@drejohnson Use https://github.com/atheycreek/atheycreek/ if you are interested in a CD implementation on a new version of Symphony. We are at `2.6.0-rc1`.
