### ISSUE TITLE
include.install.php is missing

### ISSUE THREAD

**Issue by decadeofdefeat** [jdsimcoe/churchdeploy#8]
The symphony/lib/toolkit/include.install.php file is missing from current master repository. It should be kept in there so that the install will work. Without the include, the install.php does nothing, just shows a blank page.

**Comment by decadeofdefeat** [comment]
Nevermind, I see that I should install 1.0 and then upgrade to 2.0 or master.

**Comment by jdsimcoe** [comment]
Curious as to how you found Church Deploy and what you plan on using it for. I'm trying to get more developers actively working on the project.

**Comment by decadeofdefeat** [comment]
I'm working as a full time web developer for a church in Buffalo, NY (www.thechapel.com). I'm currently researching PHP frameworks as our current site is very large and we don't use a framework at all. I stumbled upon atheycreek.com a while ago and have been sorta keeping up with your project. I'm not sure if Symphony CMS is for me, as I'm unfamiliar with XLST, but I can certainly contribute if I have some time.

**Comment by jdsimcoe** [comment]
Cool, I dig your site and the look of your church!

XSLT is powerful and the beauty is that it is tag-based like HTML, so it is
really easy to begin learning and very powerful. A long-standing member of
the Symphony community Brian Zerangue (
http://www.getsymphony.com/get-involved/member/bzerangue/) is helping me do
some work in cleaning up the core. We are adding clean URLs and I am doing
some massive work on the Athey Creek theme which I will eventually port
over to Anchor that is built on Boostrap 3.0RC1, with offcanvas menu and
several other features. Member login, event registration/payment, blogs,
better multipoint maps and more are on the horizon.

Take a look at our current progress:

http://dev.atheycreek.com/

If you want a walkthrough of the CMS, I can help get you oriented to
Symphony and XSLT. Symphony is an incredibly powerful framework that rivals
anything on the market (outside Rails and the like) for extensibility, a
robust dev community, and lots of forward-thinking structure and layout. I
have used Wordpress and ExpressionEngine and can say that Symphony blows
other CMS systems out of the water for its flexibility.

Personally, it had a bit of a learning curve for me, but once that hurdle
was overcome, it has proved to be an essential resource in building
websites for clients.

## 

_I am one of *_thesimcoes.net→ http://thesimcoes.net/*

_dtr.mn→_  http://dtr.mn/_with me to know Jesus_

**Comment by decadeofdefeat** [comment]
Yeah I'd be interested to walk through the CMS if you have time. My email is mgoldsmith@thechapel.com
